services:
  quantum_order:
    image: quantum-order
    container_name: quantum-order
    build:
      context: .
      dockerfile: docker/8.2/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    environment:
      DB_Connection: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: quantumorder_system
    depends_on:
      - db
    command: ['apache2-foreground']
    
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: quantumorder_system
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
        - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    